version: "3.8"

services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - db-data:/var/lib/postgresql/data
    init: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - ./frontend/mount:/frontend
    init: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - 3333:3333
      - 5555:5555
    restart: on-failure
    env_file:
      - .env
    networks:
      - matcha
    depends_on:
      - dev-db
    volumes:
      - ./backend/mount:/backend
    init: true

volumes:
  db-data:
    name: db-data

networks:
  matcha:
    name: matcha
